# Site settings
timezone: Europe/Warsaw
title: Luka5z's GitHub page 
email: lzachulski@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luka5z.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  luka5z

# Build settings
markdown: kramdown

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "default"
      author: "Luka5z"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "Luka5z"

